//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoredProcedureCrud.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emplo
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string EmpCompany { get; set; }
        public int EmpSalary { get; set; }
        public string EmpDepartment { get; set; }
    }
}
